# Generated by Django 4.2.7 on 2023-12-04 10:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('release_date', models.DateField()),
                ('listeners_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('age', models.DateField()),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('listeners_per_month', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=210))),
                ('listened', models.IntegerField(default=0)),
                ('music', models.FileField(upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
            ],
            options={
                'verbose_name_plural': 'Music',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ManyToManyField(related_name='tracks', to='music.author'),
        ),
    ]
