# Generated by Django 4.2.7 on 2023-12-06 17:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='viewers',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
