# Generated by Django 4.2.7 on 2023-12-06 17:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotmusic',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newmusic',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
